### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D10"
}

### Calculate Price with invalid coupon
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D1000"
}

### Calculate Price with invalid product and tax number
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
"product": 10,
"taxNumber": "",
"couponCode": "D15"
}


### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "D20",
  "paymentProcessor": "paypal"
}

### Execute Purchase with invalid tax number
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IB12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

### Execute Purchase with invalid payment processor
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "FRAB12345678900",
  "couponCode": "D15",
  "paymentProcessor": "str1pe"
}
